spring:
  profiles:
    active: dev
    include:
      - base-addi
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/week3__dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
        use_sql_comments: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: halojw301@gmail.com
    password: NEED_TO_EMPTY
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    root: info
    com.ll.ebook.app: debug
    org.hibernate.type.descriptor.sql: trace
custom:
  site:
    name: M-BOOKS
    baseUrl: "http://localhost:8010"
